title: Rishikesan Ravichandran
logo: /assets/images/linkedin_cropped.jpg
description:  I enjoy learning about things that I am not very familiar with, and I make an effort to understand them fundamentally. This gives me the advantage to follow my heart with a more rational mind.
show_downloads: true
theme: pages-themes-minima
