title: Rishikesan Ravichandran
logo: /assets/images/linkedin_cropped.jpg
description:  Follow your heart with a rational mind.
contact: Contact: rravichandran@ucdavis.edu
show_downloads: false
theme: jekyll-theme-minimal
